[package]
name = "websocket_server"
version = "0.1.0"
authors = ["Alexander Wilkinson <alexwilkinson@gmail.com>"]

[dependencies]
mio = "0.5"
http-muncher = "0.2.0"
rustc-serialize = "0.3.15"
sha1 = "0.1.1"